{% set name = "heavyai" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/heavyai-{{ version }}.tar.gz
  sha256: 62311655efcea6c998ca093ccec11d3f7fc99fb048d49c1a05532652d70af2b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - flit-core
  run:
    - importlib_metadata
    - numpy
    - pandas
    - pyarrow >=3.0.0
    - pyomniscidb >=5.5.0
    - python >=3.7
    - shapely

test:
  imports:
    - heavyai

about:
  home: https://github.com/heavyai/heavyai
  summary: Data science toolkit support for HeavyDB
  dev_url: https://github.com/heavyai/heavyai
  doc_url: https://heavyai.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE.md
  description: |
    This package enables using common Python data science toolkits with
    HeavyDB. It brings dataframe support on CPU and GPU as well as
    support for arrow.

extra:
  recipe-maintainers:
    - tupui
    - pearu
    - andrewseidl
